import Head from 'next/head'

export default function Contacts() {

  async function handleSubmit (event) {
    event.preventDefault();
    const form = new FormData(event.target);
    console.log(form.get('email'), form.get('body'))
    // esegui la funzione send-email nella cartella api
    const response = await fetch('/api/send-email') // await = aspetta che la funzione finisca
    console.log(await response.json())
  }

  return (
    <>
      <Head>
        <title>Contatti</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <form style={{ display: 'flex' }} onSubmit={handleSubmit}>
        <input type="email" name="email" style={{ border: '1px solid black' }}/>
        <textarea name="body" style={{ border: '1px solid black' }}/>
        <button type="submit">Invia</button>
      </form>
    </>
  )
}