import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'


export default function Home() {
  const [counter,setCounter] = useState(0)
  return (
    <div>
      <Head>
        <title>Create Next App {counter}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        CIAO
        <button onClick={() => setCounter(counter+1)}>Click</button>
        <Link href="/pagina2">Vai a pagina 2</Link>

    </div>
  )
}