import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'


export default function Home() {
  const [counter,setCounter] = useState(0)
  return (
    <div>
      <Head>
        <title>Create Next App {counter}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="top-bar">
      <p>L.I.</p>
      <button>Loremipsum</button>
        
      </div>
        <div className="hero">
          <div className="campoTestuale">
            <h1>Lorem Ipsum</h1>
            <h3>Lorem ipsum dolor sit amet, consectetur adipiscing</h3>
          </div>
        </div>
        <h2>
          Lorem Ipsum
        </h2>

    </div>
  )
}