import Head from 'next/head'

export default function Pagina2() {
  return (
    <div>
      <Head>
        <title>Pagina 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        pagina 2
    </div>
  )
}